/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.ArtistaDAO;
import Model.Artista;
import javax.swing.JOptionPane;

/**
 *
 * @author eddie
 */
public class ArtistaForm extends javax.swing.JFrame {

    /**
     * Creates new form ArtistaView
     */
    public ArtistaForm() {
        dao.Conexao();
        initComponents();
    }
    
    ArtistaDAO dao = new ArtistaDAO();
    Artista art = new Artista();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        textAltura = new javax.swing.JTextField();
        ButCadastrar = new javax.swing.JButton();
        ButConsultar = new javax.swing.JButton();
        ButAlterar = new javax.swing.JButton();
        ButExcluir = new javax.swing.JButton();
        ButListar = new javax.swing.JButton();
        ButSair = new javax.swing.JButton();
        ButIMC = new javax.swing.JButton();
        textIMC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        Idade = new javax.swing.JLabel();
        textIdade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textPeso = new javax.swing.JTextField();
        ButLimpar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Idade1 = new javax.swing.JLabel();
        textGlicemia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textColesterol = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textCreatinina = new javax.swing.JTextField();
        textPA = new javax.swing.JTextField();
        textRem = new javax.swing.JTextField();
        Idade2 = new javax.swing.JLabel();
        textFreq = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textID1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textNomeArt = new javax.swing.JTextField();
        Idade3 = new javax.swing.JLabel();
        textDataNasc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textOuvintes = new javax.swing.JTextField();
        ButExcluir1 = new javax.swing.JButton();
        ButCadastrar1 = new javax.swing.JButton();
        ButAlterar1 = new javax.swing.JButton();
        ButListar1 = new javax.swing.JButton();
        ButLimpar1 = new javax.swing.JButton();
        ButConsultar1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        ButSair1 = new javax.swing.JButton();
        textAlter_Ego = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButCadastrar.setText("CADASTRAR");
        ButCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCadastrarActionPerformed(evt);
            }
        });

        ButConsultar.setText("CONSULTAR");
        ButConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButConsultarActionPerformed(evt);
            }
        });

        ButAlterar.setText("ALTERAR");
        ButAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAlterarActionPerformed(evt);
            }
        });

        ButExcluir.setText("EXCLUIR");
        ButExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButExcluirActionPerformed(evt);
            }
        });

        ButListar.setText("LISTAR");
        ButListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButListarActionPerformed(evt);
            }
        });

        ButSair.setText("SAIR");
        ButSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSairActionPerformed(evt);
            }
        });

        ButIMC.setText("Calcular IMC");
        ButIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButIMCActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario");

        jLabel2.setText("Nome");

        textNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeActionPerformed(evt);
            }
        });

        Idade.setText("Idade");

        jLabel4.setText("Peso");

        ButLimpar.setText("LIMPAR");
        ButLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButLimparActionPerformed(evt);
            }
        });

        jLabel5.setText("Altura");

        Idade1.setText("Glicemia");

        jLabel6.setText("Colesterol");

        jLabel7.setText("Creatinina");

        jLabel3.setText("PA");

        textPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPAActionPerformed(evt);
            }
        });

        Idade2.setText("Frequencia na Academia");

        jLabel9.setText("Remedios Diarios");

        jLabel8.setText("ID");

        textID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(Idade1)))
                        .addGap(29, 29, 29)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textGlicemia)
                            .addComponent(textPA)
                            .addComponent(textColesterol, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(Idade)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addComponent(jLabel8))
                        .addGap(28, 28, 28)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textID)
                            .addComponent(textIdade)
                            .addComponent(textAltura)
                            .addComponent(textNome)
                            .addComponent(textPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ButExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButCadastrar))
                                .addGap(25, 25, 25)
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButListar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButConsultar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Idade2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFreq)
                            .addComponent(textRem, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textCreatinina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButSair)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(474, 474, 474))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textCreatinina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Idade2)
                            .addComponent(textFreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(30, 30, 30)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textIMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButIMC))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButCadastrar)
                            .addComponent(ButListar)
                            .addComponent(ButConsultar))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButAlterar)
                            .addComponent(ButLimpar)
                            .addComponent(ButExcluir)))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Idade)
                            .addComponent(textIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Idade1)
                            .addComponent(textGlicemia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textColesterol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(ButSair)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setText("ID Artista");

        textID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textID1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Nome Artista");

        textNomeArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeArtActionPerformed(evt);
            }
        });

        Idade3.setText("Data de Nascimento");

        jLabel12.setText("Ouvintes");

        ButExcluir1.setText("EXCLUIR");
        ButExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButExcluir1ActionPerformed(evt);
            }
        });

        ButCadastrar1.setText("CADASTRAR");
        ButCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCadastrar1ActionPerformed(evt);
            }
        });

        ButAlterar1.setText("ALTERAR");
        ButAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAlterar1ActionPerformed(evt);
            }
        });

        ButListar1.setText("LISTAR");
        ButListar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButListar1ActionPerformed(evt);
            }
        });

        ButLimpar1.setText("LIMPAR");
        ButLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButLimpar1ActionPerformed(evt);
            }
        });

        ButConsultar1.setText("CONSULTAR");
        ButConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButConsultar1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Artista");

        ButSair1.setText("SAIR");
        ButSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSair1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Alter Ego");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ButExcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButCadastrar1))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButAlterar1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButListar1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButConsultar1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ButLimpar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textID1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                    .addComponent(textNomeArt)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Idade3)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textDataNasc)
                                    .addComponent(textOuvintes, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textAlter_Ego, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel16)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButSair1)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel16)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textNomeArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(textAlter_Ego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Idade3)
                    .addComponent(textDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(textOuvintes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButCadastrar1)
                    .addComponent(ButListar1)
                    .addComponent(ButConsultar1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButAlterar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButLimpar1)
                        .addComponent(ButExcluir1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(ButSair1)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCadastrarActionPerformed
        try {
            if (this.textNomeArt.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Nome não inserido");
            }
            else if (this.textAlter_Ego.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Alter ego não inserido");
            }
            else if (this.textDataNasc.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Data de nacimento não inserida");
            }
            else if (this.textOuvintes.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Ouvintes não inserido");
            }
            else{
                dao.Cadastrar(this.textNomeArt.getText(), this.textAlter_Ego.getText() , this.textDataNasc.getText() , Integer.parseInt(this.textOuvintes.getText()));
                this.textNomeArt.setText("");
                this.textAlter_Ego.setText("");
                this.textDataNasc.setText("");
                this.textOuvintes.setText("");
            }
        }
        catch (NumberFormatException numberFormatException){
            JOptionPane.showMessageDialog(null, "verifique se os dados foram corretamente digitados.");
        }
    }//GEN-LAST:event_ButCadastrarActionPerformed

    private void ButConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButConsultarActionPerformed
        try{
            if (this.textID.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Por favor utilize o ID para especificar o usuario a ser consulltado.");
            }
            else{
                String info= dao.Consultar(Integer.parseInt(this.textID.getText()));
                String vetor[]=info.split(";");
                this.textNomeArt.setText(vetor[0]);
                this.textAlter_Ego.setText(vetor[1]);
                this.textDataNasc.setText(vetor[2]);
                this.textOuvintes.setText(vetor[3]);
            }
        }
        catch (NumberFormatException exception){
            JOptionPane.showMessageDialog(null, "Verifique se o dado digitado realmente é um numero.");
        }
    }//GEN-LAST:event_ButConsultarActionPerformed

    private void ButAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAlterarActionPerformed
        try{
            if (this.textNomeArt.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Nome não inserido");
            }
            else if (this.textAlter_Ego.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Alter ego não inserido");
            }
            else if (this.textDataNasc.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Data de nacimento não inserida");
            }
            else if (this.textOuvintes.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Ouvintes não inserido");
            }
            else{
                dao.Alterar(Integer.parseInt(this.textID.getText()) ,this.textNomeArt.getText(), this.textAlter_Ego.getText() , this.textDataNasc.getText() , Integer.parseInt(this.textOuvintes.getText()));
                this.textNomeArt.setText("");
                this.textAlter_Ego.setText("");
                this.textDataNasc.setText("");
                this.textOuvintes.setText("");
            }
        }
        catch (NumberFormatException exception){
            JOptionPane.showMessageDialog(null, "Verifique se o dado digitado realmente é um numero.");
        }
    }//GEN-LAST:event_ButAlterarActionPerformed

    private void ButExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButExcluirActionPerformed
        try{
            if (this.textID.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Por favor utilize o ID para especificar o usuario a ser consulltado.");
            }
            else{
                dao.Excluir(Integer.parseInt(this.textID.getText()));
            }
        }
        catch (NumberFormatException exception){
            JOptionPane.showMessageDialog(null, "Verifique se o dado digitado realmente é um numero.");
        }
    }//GEN-LAST:event_ButExcluirActionPerformed

    private void ButListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButListarActionPerformed
        dao.Listar();
    }//GEN-LAST:event_ButListarActionPerformed

    private void ButSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSairActionPerformed
        new Main().setVisible(true);
        dispose();
    }//GEN-LAST:event_ButSairActionPerformed

    private void ButIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButIMCActionPerformed
       
    }//GEN-LAST:event_ButIMCActionPerformed

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeActionPerformed

    private void ButLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButLimparActionPerformed
        this.textNomeArt.setText("");
        this.textAlter_Ego.setText("");
        this.textDataNasc.setText("");
        this.textOuvintes.setText("");
    }//GEN-LAST:event_ButLimparActionPerformed

    private void textPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPAActionPerformed

    private void textIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDActionPerformed

    }//GEN-LAST:event_textIDActionPerformed

    private void textID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textID1ActionPerformed

    }//GEN-LAST:event_textID1ActionPerformed

    private void textNomeArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeArtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeArtActionPerformed

    private void ButExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButExcluir1ActionPerformed
        try{
            if (this.textID1.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Por favor utilize o ID para especificar o usuario a ser consulltado.");
            }
            else{
                dao.Excluir(Integer.parseInt(this.textID1.getText()));
            }
        }
        catch (NumberFormatException exception){
            JOptionPane.showMessageDialog(null, "Verifique se o dado digitado realmente é um numero.");
        }
    }//GEN-LAST:event_ButExcluir1ActionPerformed

    private void ButCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCadastrar1ActionPerformed
        try {
            if (this.textNomeArt.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Nome não inserido");
            }
            else if (this.textAlter_Ego.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Alter ego não inserido");
            }
            else if (this.textDataNasc.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Data de nacimento não inserida");
            }
            else if (this.textOuvintes.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Ouvintes não inserido");
            }
            else{
                dao.Cadastrar(this.textNomeArt.getText(), this.textAlter_Ego.getText() , this.textDataNasc.getText() , Integer.parseInt(this.textOuvintes.getText()));
                this.textNomeArt.setText("");
                this.textAlter_Ego.setText("");
                this.textDataNasc.setText("");
                this.textOuvintes.setText("");
            }
        }
        catch (NumberFormatException numberFormatException){
            JOptionPane.showMessageDialog(null, "verifique se os dados foram corretamente digitados.");
        }
    }//GEN-LAST:event_ButCadastrar1ActionPerformed

    private void ButAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAlterar1ActionPerformed
        try{
            if (this.textNomeArt.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Nome não inserido");
            }
            else if (this.textAlter_Ego.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Alter ego não inserido");
            }
            else if (this.textDataNasc.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Data de nacimento não inserida");
            }
            else if (this.textOuvintes.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Ouvintes não inserido");
            }
            else{
                dao.Alterar(Integer.parseInt(this.textID1.getText()) ,this.textNomeArt.getText(), this.textAlter_Ego.getText() , this.textDataNasc.getText() , Integer.parseInt(this.textOuvintes.getText()));
                this.textNomeArt.setText("");
                this.textAlter_Ego.setText("");
                this.textDataNasc.setText("");
                this.textOuvintes.setText("");
            }
        }
        catch (NumberFormatException exception){
            JOptionPane.showMessageDialog(null, "Verifique se o dado digitado realmente é um numero.");
        }
    }//GEN-LAST:event_ButAlterar1ActionPerformed

    private void ButListar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButListar1ActionPerformed
        dao.Listar();
    }//GEN-LAST:event_ButListar1ActionPerformed

    private void ButLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButLimpar1ActionPerformed
        this.textNomeArt.setText("");
        this.textAlter_Ego.setText("");
        this.textDataNasc.setText("");
        this.textOuvintes.setText("");
    }//GEN-LAST:event_ButLimpar1ActionPerformed

    private void ButConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButConsultar1ActionPerformed
        try{
            if (this.textID1.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Por favor utilize o ID para especificar o usuario a ser consulltado.");
            }
            else{
                String info= dao.Consultar(Integer.parseInt(this.textID1.getText()));
                String vetor[]=info.split(";");
                this.textNomeArt.setText(vetor[0]);
                this.textAlter_Ego.setText(vetor[1]);
                this.textDataNasc.setText(vetor[2]);
                this.textOuvintes.setText(vetor[3]);
            }
        }
        catch (NumberFormatException exception){
            JOptionPane.showMessageDialog(null, "Verifique se o dado digitado realmente é um numero.");
        }
    }//GEN-LAST:event_ButConsultar1ActionPerformed

    private void ButSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSair1ActionPerformed
        new Main().setVisible(true);
        dispose();
    }//GEN-LAST:event_ButSair1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArtistaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArtistaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArtistaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArtistaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArtistaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButAlterar;
    private javax.swing.JButton ButAlterar1;
    private javax.swing.JButton ButCadastrar;
    private javax.swing.JButton ButCadastrar1;
    private javax.swing.JButton ButConsultar;
    private javax.swing.JButton ButConsultar1;
    private javax.swing.JButton ButExcluir;
    private javax.swing.JButton ButExcluir1;
    private javax.swing.JButton ButIMC;
    private javax.swing.JButton ButLimpar;
    private javax.swing.JButton ButLimpar1;
    private javax.swing.JButton ButListar;
    private javax.swing.JButton ButListar1;
    private javax.swing.JButton ButSair;
    private javax.swing.JButton ButSair1;
    private javax.swing.JLabel Idade;
    private javax.swing.JLabel Idade1;
    private javax.swing.JLabel Idade2;
    private javax.swing.JLabel Idade3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textAlter_Ego;
    private javax.swing.JTextField textAltura;
    private javax.swing.JTextField textColesterol;
    private javax.swing.JTextField textCreatinina;
    private javax.swing.JTextField textDataNasc;
    private javax.swing.JTextField textFreq;
    private javax.swing.JTextField textGlicemia;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textID1;
    private javax.swing.JTextField textIMC;
    private javax.swing.JTextField textIdade;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textNomeArt;
    private javax.swing.JTextField textOuvintes;
    private javax.swing.JTextField textPA;
    private javax.swing.JTextField textPeso;
    private javax.swing.JTextField textRem;
    // End of variables declaration//GEN-END:variables
}
