/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.MusicaDAO;
import Model.Musica;
import javax.swing.JOptionPane;

/**
 *
 * @author eddie
 */
public class MusicaForm extends javax.swing.JFrame {

    /**
     * Creates new form MusicaForm
     */
    public MusicaForm() {
        dao.Conexao();
        initComponents();
    }
    
    MusicaDAO dao = new MusicaDAO();
    Musica mus = new Musica();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Idade3 = new javax.swing.JLabel();
        ButSair1 = new javax.swing.JButton();
        textAlbum = new javax.swing.JTextField();
        textLancamento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textOuvintes = new javax.swing.JTextField();
        ButExcluir = new javax.swing.JButton();
        ButCadastrar1 = new javax.swing.JButton();
        ButAlterar = new javax.swing.JButton();
        ButListar1 = new javax.swing.JButton();
        ButLimpar1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ButConsultar1 = new javax.swing.JButton();
        textNomeMusica = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Idade3.setText("Album");

        ButSair1.setText("SAIR");
        ButSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSair1ActionPerformed(evt);
            }
        });

        textLancamento.setText("EX: 2021.10.21");

        jLabel12.setText("Ouvintes");

        jLabel13.setText("Lancamento");

        ButExcluir.setText("EXCLUIR");
        ButExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButExcluirActionPerformed(evt);
            }
        });

        ButCadastrar1.setText("CADASTRAR");
        ButCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCadastrar1ActionPerformed(evt);
            }
        });

        ButAlterar.setText("ALTERAR");
        ButAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAlterarActionPerformed(evt);
            }
        });

        ButListar1.setText("LISTAR");
        ButListar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButListar1ActionPerformed(evt);
            }
        });

        ButLimpar1.setText("LIMPAR");
        ButLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButLimpar1ActionPerformed(evt);
            }
        });

        jLabel10.setText("ID Musica");

        textID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDActionPerformed(evt);
            }
        });

        jLabel11.setText("Nome Musica");

        ButConsultar1.setText("CONSULTAR");
        ButConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButConsultar1ActionPerformed(evt);
            }
        });

        textNomeMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeMusicaActionPerformed(evt);
            }
        });

        jLabel16.setText("Musicas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ButExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButCadastrar1))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButListar1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButConsultar1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ButLimpar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textID, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                    .addComponent(textNomeMusica)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Idade3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textAlbum)
                                    .addComponent(textOuvintes, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel16)))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButSair1)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel16)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textNomeMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(textLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Idade3)
                    .addComponent(textAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(textOuvintes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButCadastrar1)
                    .addComponent(ButListar1)
                    .addComponent(ButConsultar1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButLimpar1)
                        .addComponent(ButExcluir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(ButSair1)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSair1ActionPerformed
        new Main().setVisible(true);
        dispose();
    }//GEN-LAST:event_ButSair1ActionPerformed

    private void ButExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButExcluirActionPerformed
         try{
            if (this.textID.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Por favor utilize o ID para especificar o usuario a ser consulltado.");
            }
            else{
                dao.Excluir(Integer.parseInt(this.textID.getText()));
            }
        }
        catch (NumberFormatException exception){
            JOptionPane.showMessageDialog(null, "Verifique se o dado digitado realmente é um numero.");
        }
    }//GEN-LAST:event_ButExcluirActionPerformed

    private void ButCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCadastrar1ActionPerformed
        try {
            if (this.textNomeMusica.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Nome não inserido");
            }
            else if (this.textLancamento.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Alter ego não inserido");
            }
            else if (this.textAlbum.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Data de nacimento não inserida");
            }
            else if (this.textOuvintes.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Ouvintes não inserido");
            }
            else{
                dao.Cadastrar(this.textNomeMusica.getText(), this.textLancamento.getText() , this.textAlbum.getText() , Integer.parseInt(this.textOuvintes.getText()));
                this.textNomeMusica.setText("");
                this.textLancamento.setText("");
                this.textAlbum.setText("");
                this.textOuvintes.setText("");
            }
        }
        catch (NumberFormatException numberFormatException){
            JOptionPane.showMessageDialog(null, "verifique se os dados foram corretamente digitados.");
        }
    }//GEN-LAST:event_ButCadastrar1ActionPerformed

    private void ButAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAlterarActionPerformed
        try{
            if (this.textNomeMusica.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Nome não inserido");
            }
            else if (this.textLancamento.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Alter ego não inserido");
            }
            else if (this.textAlbum.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Data de nacimento não inserida");
            }
            else if (this.textOuvintes.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Erro, Ouvintes não inserido");
            }
            else{
                dao.Alterar(Integer.parseInt(this.textID.getText()) ,this.textNomeMusica.getText(), this.textLancamento.getText() , this.textAlbum.getText() , Integer.parseInt(this.textOuvintes.getText()));
                this.textNomeMusica.setText("");
                this.textLancamento.setText("");
                this.textAlbum.setText("");
                this.textOuvintes.setText("");
            }
        }
        catch (NumberFormatException exception){
            JOptionPane.showMessageDialog(null, "Verifique se o dado digitado realmente é um numero.");
        }
    }//GEN-LAST:event_ButAlterarActionPerformed

    private void ButListar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButListar1ActionPerformed
        dao.Listar();
    }//GEN-LAST:event_ButListar1ActionPerformed

    private void ButLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButLimpar1ActionPerformed
        this.textNomeMusica.setText("");
        this.textLancamento.setText("");
        this.textAlbum.setText("");
        this.textOuvintes.setText("");
    }//GEN-LAST:event_ButLimpar1ActionPerformed

    private void textIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDActionPerformed

    }//GEN-LAST:event_textIDActionPerformed

    private void ButConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButConsultar1ActionPerformed
        try{
            if (this.textID.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Por favor utilize o ID para especificar o usuario a ser consulltado.");
            }
            else{
                String info= dao.Consultar(Integer.parseInt(this.textID.getText()));
                String vetor[]=info.split(";");
                this.textNomeMusica.setText(vetor[0]);
                this.textLancamento.setText(vetor[1]);
                this.textAlbum.setText(vetor[2]);
                this.textOuvintes.setText(vetor[3]);
            }
        }
        catch (NumberFormatException exception){
            JOptionPane.showMessageDialog(null, "Verifique se o dado digitado realmente é um numero.");
        }
    }//GEN-LAST:event_ButConsultar1ActionPerformed

    private void textNomeMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeMusicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeMusicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButAlterar;
    private javax.swing.JButton ButCadastrar1;
    private javax.swing.JButton ButConsultar1;
    private javax.swing.JButton ButExcluir;
    private javax.swing.JButton ButLimpar1;
    private javax.swing.JButton ButListar1;
    private javax.swing.JButton ButSair1;
    private javax.swing.JLabel Idade3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JTextField textAlbum;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textLancamento;
    private javax.swing.JTextField textNomeMusica;
    private javax.swing.JTextField textOuvintes;
    // End of variables declaration//GEN-END:variables
}
